# Generated by Django 3.2 on 2021-04-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0003_follow'),
        ('api', '0002_comment_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Car',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='category',
            new_name='brand',
        ),
    ]
